export const HttpResponse = {
  OK: "OK",
  SERVER_ERROR: "internal server Error!",
  USER_EXIST: "User already exist",
  USER_CREATION_FAILED: "User Creation Failed",
  USER_NOT_FOUND: "User not Found",
  USER_BLOCKED: "User blocked",
  INVALID_CREDNTIALS: "Invalid Credentials",
  CREATED: "Created Successfully",
  LOGGED_IN_SUCCESSFULLY: "User Logged In Successfully",
  LOGGED_OUT: "User Logged Out",
  ACCESS_TOKEN_EXPIRED: "Access Token Expired",
  REFRESH_TOKEN_EXPIRED: "Refresh Token Expired",
  UNAUTHORIZED: "Unauthorized Access, Please Login First",
  TOKEN_NOT_FOUND: "Token not Found",
  ACCESS_DENIED: "Access Denied!",
  ITEM_EXIST: "Item Already Exist",
  INVALID_ID: "Invalid id",
  ITEM_NOT_FOUND: "Item not Found !",
  ORDER_EXIST: " You have already Purchased this Course !",
  FAILED_TO_CREATE_REVIE: "failed to add your review !",
  CHAT_NOT_FOUND: "Chat not found ",
  CHAT_ID_Required: "Chat id  required",
  NOT_PERMINTED: "Not permited to join this chat",
};
